---
- hosts: all
  vars:
    pwsh_url: "https://github.com/PowerShell/PowerShell/releases/tag/v6.0.1/"
    pwsh_msi: "PowerShell-6.0.1-win-x64.msi"
    pwsh_rpm: "powershell-6.0.1-1.rhel.7.x86_64.rpm"
    pwsh_repo: "https://packages.microsoft.com/config/rhel/7/prod.repo"
    win_dest: 'C:\Temp\'
  tasks:
    - block:
      - name: OS Declaration
        debug:
          msg: "Running on Windows Clients"
      - name: Make Download Folder
        win_file:
          path: "{{ win_dest }}"
          state: directory
      - name: Download PowerShell Core
        win_get_url:
          url: "{{ pwsh_url }}{{ pwsh_msi }}"
          dest: "{{ win_dest }}"
      - name: Install PowerShell Core
        win_package:
          path: "{{ win_dest }}{{ pwsh_msi }}"
          state: present
      when: ansible_os_family == "Windows"
    - block:
      - name: OS Declaration
        debug:
          msg: "Running on RedHat/Centos Clients"
      #- name: Register Microsoft RedHat Repo
      #  shell: curl {{ pwsh_repo }} | /etc/yum.repos.d/microsoft.repo
      - name: Register Microsoft RedHat Repo
        get_url:
          url: "{{ pwsh_repo }}"
          dest: /etc/yum.repos.d/microsoft.repo
      - name: Install PowerShell Core
        yum:
          name: "powershell"
          state: present
      - name: Add Subsystem to SSHD_conf
        lineinfile:
          path: /etc/ssh/sshd_config
          insertafter: "# override default of no subsystems"
          line: "Subsystem	powershell	/usr/bin/pwsh -sshs -NoLogo -NoProfile"
      - name: Restart SSHD
        service:
          name: sshd
          state: restarted
      when: ansible_os_family == "RedHat"
    - name: Install Pester Module
      # This can be brought out once all OS families are working.
      command: pwsh -command { Install-Module -Name Pester -Force -SkipPublisherCheck }
