---
- hosts: centos.test.local
  vars:
    plexRPM: "https://downloads.plex.tv/plex-media-server/1.12.0.4829-6de959918/plexmediaserver-1.12.0.4829-6de959918.x86_64.rpm"
    checkSum: "sha256:5d5977dab72a31e51b58273b83175a87d61edec1b6ce6c43b686219e75e25d3a"
    localDest: "/tmp/plexmediaserver.rpm"
  tasks:
  - name: Download PlexRPM
    get_url:
      url: "{{ plexRPM }}"
      dest: "{{ localDest }}"
      checksum: "{{ checkSum }}"
  - name: Install PlexMediaServer
    yum:
      name: "{ localDest }"
      state: present
  - name: Start Plex Media Server
    service:
      name: plexmediaserver
      enabled: true
      state: restarted
  - name: Open Port for Plex
    firewalld:
      port: 32400/tcp
      permanent: true
      state: enabled
  - name: Restart Firewall
    service:
      name: firewalld
      state: restarted
# Note, add NFS steps.
# firewall-cmd --permanent --zone=public --add-service=nfs
# firewall-cmd --reload
# yum install nfs-utils -y 
# mount 192.168.1.2:/mnt/Media /mnt/nfs/media/
# edit fstab: 192.168.1.2:/mnt/Media  /mnt/nfs/media/  nfs  rw,sync,hard,intr  0  0
