---
- hosts: plex
  vars:
    plexRPM: "https://downloads.plex.tv/plex-media-server/1.12.0.4829-6de959918/plexmediaserver-1.12.0.4829-6de959918.x86_64.rpm"
    checkSum: "sha256:5d5977dab72a31e51b58273b83175a87d61edec1b6ce6c43b686219e75e25d3a"
    localDest: "/tmp/plexmediaserver.rpm"
  tasks:
  - name: Download PlexRPM
    get_url:
      url: "{{ plexRPM }}"
      dest: "{{ localDest }}"
      checksum: "{{ checkSum }}"
  - name: Install PlexMediaServer
    yum:
      name: "{{ localDest }}"
      state: present
  - name: Start PlexMediaServer
    service:
      name: plexmediaserver
      enabled: true
      state: restarted
  - name: Add Plex Firewall service
    copy:
      dest: /etc/firewalld/services/plex.xml
      content: |
               <service>
                 <short>plex</short>
                 <description>PlexMediaServer Service</description>
                 <port protocol="tcp" port="32400"/>
               </service>
  - name: Reload Firewalld (Report Plex network service)
    service:
      name: firewalld
      state: restarted
  - name: Open Port for Plex
    firewalld:
      service: plex
      permanent: true
      state: enabled
  - name: Reload Firewalld (Start Plex network service)
    service: 
      name: firewalld
      state: restarted
