---
# https://sabnzbd.org/wiki/installation/install-fedora-centos-rhel
# https://centos.pkgs.org/6/forensics-x86_64/unrar-5.3.0-1.el6.x86_64.rpm.html
- hosts: sabnzb
  vars:
    unrar_link: "https://forensics.cert.org/centos/cert/7/x86_64//unrar-5.3.0-1.el7.x86_64.rpm"
    sab_link: "https://github.com/sabnzbd/sabnzbd"
    sab_path: "/opt/sabnzbd"
  tasks:
  - name: Install Epel Release
    yum:
      name: epel-release
      state: present
  - name: Install Prereqs
    yum:
      name: "{{ item }}"
      state: present
    with_items:
    - python-pip
    - git
    - par2cmdline
    - python-cheetah
  - name: Install Pip Modules
    pip:
      name: "{{ item }}"
    with_items:
    - sabyenc
    - yenc
  - name: Install UnRar
    yum:
      name: "{{ unrar_link }}"
      state: present
  - name: Create installation location
    file:
      path: "{{ sab_path }}"
      state: directory
  - name: Clone SabNZBd Master
    git:
      repo: "{{ sab_link }}"
      dest: "{{ sab_path }}"
  - name: Add language files
    command: python tools/make_mo.py
    args:
      chdir: "{{ sab_path }}"
  - name: Create usenet User
    user:
      name: usenet
      state: present
      shell: /sbin/nologin
  - name: Set SabNZBd file Owner
    file:
      recurse: yes
      path: "{{ sab_path }}"
      owner: usenet
      group: usenet
  - name: Create sabnzbd.service
    copy:
      dest: /etc/systemd/system/sabnzbd.service
      content: |
               #
               # Systemd unit file for SABnzbd
               #
               [Unit]
               Description=SABnzbd Daemon
               
               [Service]
               Type=forking
               User=usenet
               Group=usenet
               ExecStart=/usr/bin/python {{ sab_path}}/SABnzbd.py --daemon --config-file={{ sab_path }}/sabnzbd_config.ini -s 0.0.0.0
               GuessMainPID=no
               
               [Install]
               WantedBy=multi-user.target
  - name: Create sabnzbd Network Service
    copy:
      dest: /etc/firewalld/services/sabnzbd.xml
      content: |
               <service>
                 <short>sabnzbd</short>
                 <description>SabNZBd Download Service</description>
                 <port protocol="tcp" port="8080"/>
               </service>
  - name: Refresh Firewall (updating firewall)
    service:
      name: firewalld
      state: restarted
  - name: Add sabnzbd to Firewall
    firewalld:
      service: sabnzbd
      permanent: true
      state: enabled
  - name: Refresh Firewall (enabling service)
    service:
      name: firewalld
      state: restarted
  - name: Start Sabnzbd Service
    service:
      name: sabnzbd
      enabled: yes
      state: restarted
